In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from icecream import ic
import seaborn as sns
import lazypredict

___

# Full Dataset

In [2]:
filename = r"../../data/raw/term-deposit-marketing-2020.csv"
df = pd.read_csv(filename)

In [3]:
from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split

# format data
X = df.copy()
Y = X.y
X = X.drop(["y"], axis=1)

# Split into train and hold-out test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [4]:
clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

In [7]:
models.sort_values("ROC AUC", ascending=False)

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,Time Taken
Model,,,,,,,
RandomForestClassifier,0.938375,0.668133,0.942589,0.930220,0.928162,0.938375,2.832771
CalibratedClassifierCV,0.935375,0.633688,0.937176,0.924089,0.922346,0.935375,0.931792
LinearSVC,0.933375,0.589372,0.937130,0.916331,0.917460,0.933375,0.419863
LogisticRegression,0.936125,0.635694,0.935790,0.924870,0.923481,0.936125,0.391062
RidgeClassifier,0.931125,0.562537,0.933088,0.910141,0.912151,0.931125,0.306418
RidgeClassifierCV,0.931125,0.562537,0.933088,0.910141,0.912151,0.931125,0.264512
LinearDiscriminantAnalysis,0.935000,0.703147,0.932980,0.931013,0.928411,0.935000,0.336395
SGDClassifier,0.935000,0.628682,0.932270,0.923186,0.921544,0.935000,0.364234
ExtraTreesClassifier,0.934375,0.621939,0.931750,0.921862,0.920277,0.934375,2.878946
NearestCentroid,0.871125,0.791240,0.921658,0.892002,0.927036,0.871125,0.362213
AdaBoostClassifier,0.928250,0.593017,0.917543,0.913667,0.909374,0.928250,2.318484
SVC,0.932625,0.570552,0.909516,0.912552,0.916096,0.932625,13.767978
BaggingClassifier,0.935125,0.671987,0.903532,0.928226,0.925179,0.935125,1.617410
Perceptron,0.932625,0.694661,0.875033,0.928527,0.925746,0.932625,0.247404
LabelPropagation,0.920500,0.663307,0.865297,0.917065,0.914204,0.920500,43.502283
GaussianNB,0.769250,0.795603,0.852203,0.822738,0.927363,0.769250,0.222192
KNeighborsClassifier,0.932125,0.631136,0.837454,0.921508,0.918166,0.932125,2.573714
BernoulliNB,0.922125,0.563293,0.836579,0.905140,0.897304,0.922125,0.295465
LabelSpreading,0.920750,0.662641,0.833121,0.917171,0.914218,0.920750,65.054183
PassiveAggressiveClassifier,0.930625,0.541450,0.801416,0.905428,0.911945,0.930625,0.247295
DecisionTreeClassifier,0.919250,0.712277,0.712277,0.920375,0.921572,0.919250,0.407935
ExtraTreeClassifier,0.905250,0.631870,0.631870,0.903917,0.902637,0.905250,0.237963
DummyClassifier,0.928000,0.500000,0.500000,0.893344,0.861184,0.928000,0.195810

___

# no NA dataset

In [9]:
filename = r"../../data/processed/no_cat_unknown.csv"
no_na_df = pd.read_csv(filename)

In [10]:
from lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split

# format data
X = no_na_df.copy()
Y = X.y
X = X.drop(["y"], axis=1)

# Split into train and hold-out test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [11]:
clf = LazyClassifier(verbose=0, ignore_warnings=True, custom_metric=None)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

In [12]:
models.sort_values("ROC AUC", ascending=False)

,Accuracy,Balanced Accuracy,ROC AUC,F1 Score,Precision,Recall,Time Taken
Model,,,,,,,
RandomForestClassifier,0.923369,0.662722,0.933153,0.914207,0.911026,0.923369,2.014561
LinearSVC,0.922229,0.607847,0.920855,0.905209,0.905657,0.922229,0.198258
CalibratedClassifierCV,0.921848,0.641797,0.920854,0.910332,0.907322,0.921848,0.488759
RidgeClassifierCV,0.921658,0.585433,0.920274,0.900567,0.904854,0.921658,0.177050
RidgeClassifier,0.922609,0.591981,0.920230,0.902480,0.906751,0.922609,0.157744
LinearDiscriminantAnalysis,0.920517,0.693311,0.920224,0.915658,0.912478,0.920517,0.230675
LogisticRegression,0.923179,0.640516,0.919077,0.911076,0.908791,0.923179,0.208872
SVC,0.922799,0.630261,0.917801,0.909287,0.907562,0.922799,8.351033
ExtraTreesClassifier,0.923560,0.634696,0.915613,0.910484,0.908880,0.923560,2.345628
NearestCentroid,0.872409,0.771485,0.910073,0.887981,0.912978,0.872409,0.186840
AdaBoostClassifier,0.918806,0.626068,0.906659,0.905936,0.902223,0.918806,1.511023
SGDClassifier,0.921848,0.587546,0.905702,0.901116,0.905189,0.921848,0.248229
BaggingClassifier,0.920137,0.685066,0.895836,0.914501,0.911047,0.920137,1.017051
LabelPropagation,0.908157,0.668468,0.849863,0.904236,0.901050,0.908157,13.081089
BernoulliNB,0.915003,0.576770,0.849648,0.894803,0.891201,0.915003,0.183299
KNeighborsClassifier,0.916524,0.635872,0.837771,0.905842,0.901203,0.916524,0.546371
LabelSpreading,0.908348,0.668572,0.832597,0.904378,0.901165,0.908348,18.964317
PassiveAggressiveClassifier,0.904925,0.667705,0.826401,0.901943,0.899355,0.904925,0.162040
GaussianNB,0.907207,0.663929,0.815176,0.903074,0.899726,0.907207,0.166019
Perceptron,0.914432,0.538281,0.796689,0.885459,0.884857,0.914432,0.158025
DecisionTreeClassifier,0.905685,0.713330,0.713330,0.906968,0.908337,0.905685,0.279848
ExtraTreeClassifier,0.891995,0.642550,0.642550,0.890537,0.889146,0.891995,0.190601
DummyClassifier,0.914242,0.500000,0.500000,0.873284,0.835839,0.914242,0.127587